-- MySQL Script generated by MySQL Workbench
-- Mon Dec 18 16:49:25 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `pravo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pravo` ;

CREATE TABLE IF NOT EXISTS `pravo` (
  `id_pravo` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `vaha` INT NOT NULL,
  PRIMARY KEY (`id_pravo`),
  UNIQUE INDEX `id_pravo_UNIQUE` (`id_pravo` ASC),
  UNIQUE INDEX `nazev_UNIQUE` (`nazev` ASC),
  UNIQUE INDEX `vaha_UNIQUE` (`vaha` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uzivatele`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uzivatele` ;

CREATE TABLE IF NOT EXISTS `uzivatele` (
  `id_uzivatel` INT NOT NULL AUTO_INCREMENT,
  `id_pravo` INT NOT NULL,
  `jmeno` VARCHAR(50) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `login` VARCHAR(30) NOT NULL,
  `heslo` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(30) NULL,
  PRIMARY KEY (`id_uzivatel`),
  UNIQUE INDEX `iduzivatele_UNIQUE` (`id_uzivatel` ASC),
  INDEX `fk_uzivatel_pravo_id_pravo_idx` (`id_pravo` ASC),
  UNIQUE INDEX `nick_UNIQUE` (`login` ASC),
  UNIQUE INDEX `foto_UNIQUE` (`foto` ASC),
  CONSTRAINT `fk_uzivatel_pravo_id_pravo`
    FOREIGN KEY (`id_pravo`)
    REFERENCES `pravo` (`id_pravo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hry` ;

CREATE TABLE IF NOT EXISTS `hry` (
  `id_hry` INT NOT NULL AUTO_INCREMENT,
  `nazev_hry` VARCHAR(50) NOT NULL,
  `zanr` VARCHAR(30) NOT NULL,
  `foto_hry` VARCHAR(50) NULL,
  `popisek_hry` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`id_hry`),
  UNIQUE INDEX `id_hry_UNIQUE` (`id_hry` ASC),
  UNIQUE INDEX `nazev_hry_UNIQUE` (`nazev_hry` ASC),
  UNIQUE INDEX `foto_hry_UNIQUE` (`foto_hry` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `recenze`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `recenze` ;

CREATE TABLE IF NOT EXISTS `recenze` (
  `id_recenze` INT NOT NULL AUTO_INCREMENT,
  `id_hry` INT NOT NULL,
  `nazev_hry` VARCHAR(50) NOT NULL,
  `id_uzivatel` INT NOT NULL,
  `login` VARCHAR(30) NOT NULL,
  `hodnoceni` INT NOT NULL,
  `recenze_text` VARCHAR(2000) NOT NULL,
  `datum` DATETIME NOT NULL,
  PRIMARY KEY (`id_recenze`),
  UNIQUE INDEX `id_recenze_UNIQUE` (`id_recenze` ASC),
  INDEX `fk_recenze_hry_id_hry_idx` (`id_hry` ASC),
  INDEX `fk_recenze_uzivatele_id_uzivatel_idx` (`id_uzivatel` ASC),
  INDEX `fk_recenze_uzivatele_login_idx` (`login` ASC),
  INDEX `fk_recenze_hry_nazev_hry_idx` (`nazev_hry` ASC),
  CONSTRAINT `fk_recenze_hry_id_hry`
    FOREIGN KEY (`id_hry`)
    REFERENCES `hry` (`id_hry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recenze_uzivatele_id_uzivatel`
    FOREIGN KEY (`id_uzivatel`)
    REFERENCES `uzivatele` (`id_uzivatel`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recenze_uzivatele_login`
    FOREIGN KEY (`login`)
    REFERENCES `uzivatele` (`login`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_recenze_hry_nazev_hry`
    FOREIGN KEY (`nazev_hry`)
    REFERENCES `hry` (`nazev_hry`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pravo`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (1, 'SuperAdmin', 20);
INSERT INTO `pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (2, 'Admin', 15);
INSERT INTO `pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (3, 'Recenzert', 10);
INSERT INTO `pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (4, 'Autor', 5);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uzivatele`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `uzivatele` (`id_uzivatel`, `id_pravo`, `jmeno`, `prijmeni`, `login`, `heslo`, `email`, `foto`) VALUES (1, 1, 'Hlavní správce', DEFAULT, 'admin', 'admin', 'SuperAdmin@seznam.cz', NULL);
INSERT INTO `uzivatele` (`id_uzivatel`, `id_pravo`, `jmeno`, `prijmeni`, `login`, `heslo`, `email`, `foto`) VALUES (2, 3, 'Pokusný recenzent', DEFAULT, 'recenzent1', 'recenzent1', 'Recenzent@seznam.cz', NULL);
INSERT INTO `uzivatele` (`id_uzivatel`, `id_pravo`, `jmeno`, `prijmeni`, `login`, `heslo`, `email`, `foto`) VALUES (3, 4, 'Pokusný autor', DEFAULT, 'autor1', 'autor', 'Autor@seznam.cz', NULL);

COMMIT;

