-- MySQL Script generated by MySQL Workbench
-- Tue Nov 28 09:48:18 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `pravo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pravo` ;

CREATE TABLE IF NOT EXISTS `pravo` (
  `id_pravo` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `vaha` INT NOT NULL,
  PRIMARY KEY (`id_pravo`),
  UNIQUE INDEX `id_pravo_UNIQUE` (`id_pravo` ASC),
  UNIQUE INDEX `nazev_UNIQUE` (`nazev` ASC),
  UNIQUE INDEX `vaha_UNIQUE` (`vaha` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uzivatele`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uzivatele` ;

CREATE TABLE IF NOT EXISTS `uzivatele` (
  `id_uzivatel` INT NOT NULL AUTO_INCREMENT,
  `id_pravo` INT NOT NULL,
  `jmeno` VARCHAR(50) NOT NULL,
  `prijmeni` VARCHAR(45) NOT NULL,
  `login` VARCHAR(30) NOT NULL,
  `heslo` VARCHAR(60) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `foto` VARCHAR(30) NULL,
  PRIMARY KEY (`id_uzivatel`),
  UNIQUE INDEX `iduzivatele_UNIQUE` (`id_uzivatel` ASC),
  INDEX `fk_uzivatel_pravo_id_pravo_idx` (`id_pravo` ASC),
  UNIQUE INDEX `nick_UNIQUE` (`login` ASC),
  UNIQUE INDEX `foto_UNIQUE` (`foto` ASC),
  CONSTRAINT `fk_uzivatel_pravo_id_pravo`
    FOREIGN KEY (`id_pravo`)
    REFERENCES `pravo` (`id_pravo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zanry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zanry` ;

CREATE TABLE IF NOT EXISTS `zanry` (
  `id_zanry` INT NOT NULL AUTO_INCREMENT,
  `nazev_zanru` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_zanry`),
  UNIQUE INDEX `id_zanry_UNIQUE` (`id_zanry` ASC),
  UNIQUE INDEX `nazev_zanru_UNIQUE` (`nazev_zanru` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hry`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hry` ;

CREATE TABLE IF NOT EXISTS `hry` (
  `id_hry` INT NOT NULL AUTO_INCREMENT,
  `nazev_hry` VARCHAR(50) NOT NULL,
  `id_zanry` INT NOT NULL,
  `vekove_doporuceni` VARCHAR(45) NOT NULL,
  `foto_hry` VARCHAR(50) NOT NULL,
  `popisek_hry` VARCHAR(2000) NOT NULL,
  PRIMARY KEY (`id_hry`),
  UNIQUE INDEX `id_hry_UNIQUE` (`id_hry` ASC),
  UNIQUE INDEX `nazev_hry_UNIQUE` (`nazev_hry` ASC),
  UNIQUE INDEX `id_zanr_UNIQUE` (`id_zanry` ASC),
  UNIQUE INDEX `foto_hry_UNIQUE` (`foto_hry` ASC),
  CONSTRAINT `fk_hry_zanry_id_zanry`
    FOREIGN KEY (`id_zanry`)
    REFERENCES `zanry` (`id_zanry`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pravo`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (1, 'SuperAdmin', 20);
INSERT INTO `pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (2, 'Admin', 15);
INSERT INTO `pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (3, 'Recenzert', 10);
INSERT INTO `pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (4, 'Autor', 5);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uzivatele`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `uzivatele` (`id_uzivatel`, `id_pravo`, `jmeno`, `prijmeni`, `login`, `heslo`, `email`, `foto`) VALUES (1, 1, 'Hlavní správce', DEFAULT, 'admin', 'admin', 'SuperAdmin@seznam.cz', NULL);
INSERT INTO `uzivatele` (`id_uzivatel`, `id_pravo`, `jmeno`, `prijmeni`, `login`, `heslo`, `email`, `foto`) VALUES (2, 3, 'Pokusný recenzent', DEFAULT, 'recenzent1', 'recenzent1', 'Recenzent@seznam.cz', NULL);
INSERT INTO `uzivatele` (`id_uzivatel`, `id_pravo`, `jmeno`, `prijmeni`, `login`, `heslo`, `email`, `foto`) VALUES (3, 4, 'Pokusný autor', DEFAULT, 'autor1', 'autor', 'Autor@seznam.cz', NULL);

COMMIT;

