-- MySQL Script generated by MySQL Workbench
-- Sun Nov 26 16:49:13 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `pravo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pravo` ;

CREATE TABLE IF NOT EXISTS `pravo` (
  `id_pravo` INT NOT NULL AUTO_INCREMENT,
  `nazev` VARCHAR(45) NOT NULL,
  `vaha` INT NOT NULL,
  PRIMARY KEY (`id_pravo`),
  UNIQUE INDEX `id_pravo_UNIQUE` (`id_pravo` ASC) VISIBLE,
  UNIQUE INDEX `nazev_UNIQUE` (`nazev` ASC) VISIBLE,
  UNIQUE INDEX `vaha_UNIQUE` (`vaha` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uzivatele`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uzivatele` ;

CREATE TABLE IF NOT EXISTS `uzivatele` (
  `id_uzivatele` INT NOT NULL AUTO_INCREMENT,
  `id_pravo` INT NOT NULL,
  `jmeno` VARCHAR(50) NOT NULL,
  `login` VARCHAR(30) NOT NULL,
  `heslo` VARCHAR(50) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_uzivatele`),
  UNIQUE INDEX `iduzivatele_UNIQUE` (`id_uzivatele` ASC) VISIBLE,
  INDEX `fk_uzivatel_pravo_id_pravo_idx` (`id_pravo` ASC) VISIBLE,
  UNIQUE INDEX `nick_UNIQUE` (`login` ASC) VISIBLE,
  CONSTRAINT `fk_uzivatel_pravo_id_pravo`
    FOREIGN KEY (`id_pravo`)
    REFERENCES `pravo` (`id_pravo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `pravo`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (1, 'SuperAdmin', 20);
INSERT INTO `pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (2, 'Admin', 15);
INSERT INTO `pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (3, 'Recenzert', 10);
INSERT INTO `pravo` (`id_pravo`, `nazev`, `vaha`) VALUES (4, 'Autor', 5);

COMMIT;


-- -----------------------------------------------------
-- Data for table `uzivatele`
-- -----------------------------------------------------
START TRANSACTION;
INSERT INTO `uzivatele` (`id_uzivatele`, `id_pravo`, `jmeno`, `login`, `heslo`, `email`) VALUES (1, 1, 'Hlavní správce', 'admin', 'admin', 'SuperAdmin@seznam.cz');
INSERT INTO `uzivatele` (`id_uzivatele`, `id_pravo`, `jmeno`, `login`, `heslo`, `email`) VALUES (2, 3, 'Pokusný recenzent', 'recenzent1', 'recenzent1', 'Recenzent@seznam.cz');
INSERT INTO `uzivatele` (`id_uzivatele`, `id_pravo`, `jmeno`, `login`, `heslo`, `email`) VALUES (3, 4, 'Pokusný autor', 'autor1', 'autor', 'Autor@seznam.cz');

COMMIT;

